import Head from 'next/head'
import { Inter } from 'next/font/google'
import Submit from '../components/Submit'
import Layout from '../components/Layout'
import { useAuth } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] })

export default function todo() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout />
        <Submit />
      </main>
    </>
  )
}
